#24 - Template Custom Field Label Translations
DiscipleTools/disciple-tools-bulk-magic-link-sender pull request #26
Opened 2022-05-03 16:03 UTC by kodinkat

fixes #24

2022-05-05 08:03 UTC, corsacca requested changes

2022-05-05 14:06 UTC, corsacca commented on magic-link/magic-link-templates.php
>          // phpcs:disable
@kodinkat these still needed?

2022-05-05 15:15 UTC, kodinkat commented on magic-link/magic-link-templates.php
>          // phpcs:disable
Nope, refactored.. :)

2022-05-06 11:34 UTC, merged

2022-05-06 11:35 UTC, corsacca commented
Thank you @kodinkat !